services:
  web:
    image: ghcr.io/citc-club/citc-website:latest
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}
    labels:
      - "traefik.enable=true"
      # HTTPS Configuration
      - "traefik.http.routers.citc-web.rule=Host(`ccrcitclub.com`)"
      - "traefik.http.routers.citc-web.entrypoints=websecure"
      - "traefik.http.routers.citc-web.tls.certresolver=myresolver"
      - "traefik.http.services.citc-web.loadbalancer.server.port=3000"
      # HTTP Redirect to HTTPS
      - "traefik.http.routers.citc-web-http.rule=Host(`ccrcitclub.com`)"
      - "traefik.http.routers.citc-web-http.entrypoints=web"
      - "traefik.http.routers.citc-web-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - webproxy

networks:
  webproxy:
    external: true
